services:
  - type: web
    name: pdm-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd dashboard && gunicorn app:server --workers 1 --threads 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: MQTT_HOST
        sync: false
      - key: MQTT_USER
        sync: false
      - key: MQTT_PASSWORD
        sync: false
      - key: MQTT_WS_PORT
        value: "8884"
      - key: MQTT_TOPIC
        value: motor/all
